name: CNIP

on:
  workflow_dispatch:

  schedule:
    - cron: "0 18 */1 * *"

env:
  URL: http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
  PANIC: apnic
  CNIP: cnip

jobs:
  Run:
    runs-on: ubuntu-20.04

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main
          fetch-depth: 0

      - name: Run
        if: success() && !cancelled()
        run: |
          curl -s "$URL" -o "$PANIC"
          grep "apnic|CN|ipv4|" "$PANIC" | awk -F '|' '{print $4"/"32-log($5)/log(2)}' >"$CNIP"

      - name: Generate release tag
        id: tag
        if: success() && !cancelled()
        run: |
          echo "::set-output name=release_tag::CNIP"
          touch release.txt
          echo "$(date +'%Y%m%d%H%M%S')" > release.txt
          echo "FILES=$CNIP" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: success() && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.FILES }}

      - name: Remove workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
